language: node_js

node_js:
  - '8'
  - '10'

dist: trusty
sudo: required

env:
  global:
  - NODE_ENV=travis

services:
  - postgresql

before_script:
  - psql -c 'create database "trails_test";' -U postgres
  - lerna bootstrap
  - npm run pg:travis:init

script:
  - lerna run coveralls

after_script:
  - lerna run sanity
