version: '3.1'
services:
  database:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA : /var/lib/postgresql/data/pgdata